services:
  ui:
    container_name: cinema-admin-ui
    build: .
    ports:
      - 3001:3000
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    networks:
      - cinema_admin
networks:
  cinema_admin:
    name: cinema_default
    external: true
